WebsiteCongChung/WebsiteCongChung/Models/HopDongViewModels.cs
using ServiceStack.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;

namespace WebsiteCongChung.Models
{
    public class HopDongViewModel
    {
        public int Id { get; set; }
        public string SoHopDong { get; set; }
        public string SoCongChung { get; set; }
        public string MaLoaiHopDong { get; set; }
        public string HinhThucCongChung { get; set; }
        public string MaNguoiTao { get; set; }
        public string MaCongChungVien { get; set; }
        public string MaCongTacVien { get; set; }
        public string TrangThai { get; set; }
        public DateTime NgayTao { get; set; }
        public DateTime NgayDuyet { get; set; }
        public PhieuYeuCauViewModel PhieuYeuCau { get; set; }

        public HopDongViewModel()
        {
            MaLoaiHopDong = "Hợp đồng chuyển nhượng nhà đất";
        }
        public static HopDongViewModel Sample
        {
            get
            {
                return new HopDongViewModel
                {
                    Id = 1,
                    SoHopDong = "2019042300003",
                    SoCongChung = "",
                    MaLoaiHopDong = "Hợp đồng chuyển nhượng nhà đất",
                    MaNguoiTao = "",
                    HinhThucCongChung = "Trong văn phòng",
                    TrangThai = "Tạo mới",
                    PhieuYeuCau = new PhieuYeuCauViewModel
                    {
                        TenKH = "Phúc Anh",
                        CMND = "123456789",
                        HoKhau = "28 Nguyễn Thị Diệu",
                        NoiDungYeuCau = "Công chứng chuyển nhượng nhà đất"
                    }
                };
            }
        }
    }

    public class TaiSanViewModel
    {
        public string TenTaiSan;
    }

    public class PhieuYeuCauViewModel
    {
        public string TenKH { get; set; }
        public DateTime? NgaySinh { get; set; }
        public string CMND { get; set; }
        public string HoKhau { get; set; }
        public string NoiDungYeuCau { get; set; }
        public string HoSoDinhKem { get; set; }
    }

    public class NoiDungHopDong
    {
        public string MaLoaiHopDong { get; set; }
        public string NoiDung { get; set; }
        private static string result = "";
        public static IList<NoiDungHopDong> Samples
        {
            get
            {
               if (string.IsNullOrEmpty(result))
               {
                    try
                    {
                        result = File.ReadAllText("C:\\Users\\Ju\\source\\repos\\WebsiteCongChung.git\\trunk\\WebsiteCongChung\\WebsiteCongChung\\Files\\Hop.txt");
                    }
                    catch(Exception ex) { }
                }
                
                
                return new List<NoiDungHopDong>() {
                    new NoiDungHopDong()
                    {
                        MaLoaiHopDong = "",
                        NoiDung = result
                    }
                };
            }
        }
    }
}

WebsiteCongChung/WebsiteCongChung/Controllers/HopDongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteCongChung.Models;

namespace WebsiteCongChung.Controllers
{
    public class HopDongController : Controller
    {
        // GET: HopDong
        public ActionResult Index()
        {
            return View();
        }

        // GET: HopDong/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: HopDong/Xem
        public ActionResult Xem()
        {
            return View("Create", HopDongViewModel.Sample);
        }

        // GET: HopDong/Create
        [HttpPost]
        public ActionResult Create(HopDongViewModel model)
        {
            return Redirect("Xem");
            
        }

        [HttpPost]
        public ActionResult InPhieuYeuCau(PhieuYeuCauViewModel model)
        {
            if (ModelState.IsValid)
            {
                return Json("anh khong dep trai", JsonRequestBehavior.AllowGet);
            }

            return Json("anh dep trai", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetNoiDungHopDong(string maLoaiHD)
        {
            return Json(NoiDungHopDong.Samples.First(), JsonRequestBehavior.AllowGet);
        }
    }
}

WebsiteCongChung/WebsiteCongChung/Views/HopDong/Create.cshtml
@using WebsiteCongChung.Models
@model HopDongViewModel
@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/jquery.min.js")
@section Scripts {
    @Scripts.Render("~/assets/global/plugins/bootstrap-toastr/toastr.min.js")
    @Scripts.Render("~/assets/pages/scripts/ui-toastr.min.js")
    @Scripts.Render("~/Scripts/kendo.all.min.js")

}
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.516/styles/kendo.common-material.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.516/styles/kendo.material.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.516/styles/kendo.material.mobile.min.css" />

<style>
    .k-dropdown-wrap .k-input {
        display: block;
    }

    .k-dropdown-wrap .k-sprite {
        vertical-align: middle;
    }
</style>
<script id="dropdowntree-template" type="text/kendo-ui-template">
    # if (item.ImageURL != "") {#
        <image src="#: item.ImageURL #" style="width:16px; height:16px;" />
    # } #
    #: item.text #
</script>
<script id="dropdowntree-value-template" type="text/kendo-ui-template">
    <i class="fa #: spriteCssClass #"></i>
    <span> #: data.text # </span>
</script>
<div class="page-content-inner">
    <div class="row">
        <div class="col-md-12">
            <section id="loginForm">
                @using (Html.BeginForm("Create", "HopDong", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-md-12">
                        <div class="tabbable-line">
                            <ul class="nav nav-tabs ">
                                <li class="active">Thông Tin Hợp Đồng</li>
                            </ul>
                            <div class="tab-content">
                                <div class="row">
                                    <div class="actions pull-right" style="padding-bottom:10px; margin-top:-65px; margin-right:15px;">
                                        <div class="actions">
                                            <input type="submit" class="btn btn-default" value="Lưu" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label">Số Hợp Đồng</label>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.SoHopDong, new { @class = "form-control text-primary", @ReadOnly = "true" })
                                                @Html.ValidationMessageFor(m => m.SoHopDong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label">Số Công Chứng</label>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.SoCongChung, new { @class = "form-control", @ReadOnly = "true" })
                                                @Html.ValidationMessageFor(m => m.SoCongChung, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label">Loại Hợp Đồng</label>
                                            <div class="col-md-8">
                                                <div class="demo-section k-content">
                                                    <div id="dropdowntree" style="width: 100%;"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label">Trạng Thái</label>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.TrangThai, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.TrangThai, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label" style="padding-right:inherit">H.Thức Công Chứng</label>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.HinhThucCongChung, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.HinhThucCongChung, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @if (false)
                                {
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="col-md-4 control-label">Người Tạo</label>
                                                <div class="col-md-8">
                                                    @Html.TextBoxFor(m => m.SoHopDong, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.SoHopDong, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="col-md-4 control-label">Ngày Tạo</label>
                                                <div class="col-md-8">
                                                    @Html.TextBoxFor(m => m.SoCongChung, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.SoCongChung, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                }

                                @if (false)
                                {
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="col-md-4 control-label">Công Chứng Viên</label>
                                                <div class="col-md-8">
                                                    @Html.TextBoxFor(m => m.SoHopDong, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.SoHopDong, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="col-md-4 control-label">Ngày Duyệt</label>
                                                <div class="col-md-8">
                                                    @Html.TextBoxFor(m => m.SoCongChung, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.SoCongChung, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }


                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label">Cộng Tác Viên</label>
                                            <div class="col-md-8">
                                                @Html.TextBoxFor(m => m.SoHopDong, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.SoHopDong, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    @if (false)
                                    {
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="col-md-4 control-label">Tệp Đính Kèm</label>
                                                <div class="col-md-8">
                                                    @Html.TextBoxFor(m => m.SoCongChung, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(m => m.SoCongChung, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="tabbable-custom">
                            <ul class="nav nav-tabs ">
                                <li class="active">
                                    <a href="#tab_15_1" data-toggle="tab"> Phiếu Yêu Cầu </a>
                                </li>
                                <li>
                                    <a href="#tab_15_2" data-toggle="tab"> Tài Sản </a>
                                </li>
                                <li>
                                    <a href="#tab_15_3" data-toggle="tab"> Nội Dung Hợp Đồng </a>
                                </li>
                            </ul>
                            <div class="tab-content my-tab">
                                <div class="tab-pane active" id="tab_15_1">
                                    @Html.Partial("_InPhieuYeuCauPartial", new PhieuYeuCauViewModel())
                                </div>
                                <div class="tab-pane" id="tab_15_2">
                                    @Html.Partial("_TaiSanPartial", new TaiSanViewModel())
                                </div>
                                <div class="tab-pane" id="tab_15_3">
                                    @Html.Partial("_NoiDungHopDong")
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</div>


WebsiteCongChung/WebsiteCongChung/Views/HopDong/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

WebsiteCongChung/WebsiteCongChung/Views/HopDong/_InPhieuYeuCauPartial.cshtml
@using WebsiteCongChung.Models
@model PhieuYeuCauViewModel
<style>
    textarea {
        resize: none;
    }
</style>
<script src="~/Scripts/test.js"></script>
<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
@{
    {
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-2 pull-right">
                        @Ajax.ActionLink("In phiếu yêu cầu", "InPhieuYeuCau", "HopDong", new AjaxOptions()
                           {
                               HttpMethod = "POST",
                               OnComplete = "onComplete"
                           }, new { @class = "btn btn-default btn-group-justified" })
                    </div>
                </div>
            </div>
        </div>
        <div id="phieu-yeu-cau">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Ông/Bà</label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(m => m.TenKH, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.TenKH, "", new { @class = "text-danger" })
                        </div>

                        <label class="col-md-1 control-label" style="padding-right:inherit">Năm Sinh</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.NgaySinh, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NgaySinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-2 control-label">CMND/Hộ Chiếu</label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(m => m.CMND, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.CMND, "", new { @class = "text-danger" })
                        </div>

                        <label class="col-md-1 control-label" style="padding-right:inherit">Ngày Cấp</label>
                        <div class="col-md-2">
                            @Html.TextBoxFor(m => m.HoSoDinhKem, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.HoSoDinhKem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Hộ Khẩu Thường Trú</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.CMND, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.CMND, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Nội Dung Yêu Cầu</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.NoiDungYeuCau, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.NoiDungYeuCau, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Giấy Tờ Kèm Theo</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(m => m.HoSoDinhKem, new { @class = "form-control", @style = "height: 100px;" })
                            @Html.ValidationMessageFor(m => m.HoSoDinhKem, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <div id="InPhieuYeuCau" class="hidden">
        <textarea name="InPhieuYeuCauEditor" id="InPhieuYeuCauEditor" rows="10" cols="80">
        </textarea>
        <script>
            CKEDITOR.replace('InPhieuYeuCauEditor', {
                height: 500
            });
            CKEDITOR.editorConfig = function (config) {
                config.language = 'es';
                config.uiColor = '#F7B42C';
                config.toolbarCanCollapse = true;
            };
        </script>
    </div>
}

WebsiteCongChung/WebsiteCongChung/Views/HopDong/_NoiDungHopDong.cshtml
<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
<textarea name="editor1" id="editor1" rows="10" cols="80" style="height: 700px;">
</textarea>
<script>
    CKEDITOR.replace('editor1', {
        height: 500
    });
    CKEDITOR.editorConfig = function (config) {
        config.language = 'es';
        config.uiColor = '#F7B42C';
        config.toolbarCanCollapse = true;
    };
    CKEDITOR.editorConfig.tabSpaces = 10;
</script>

WebsiteCongChung/WebsiteCongChung/Views/HopDong/_TaiSanPartial.cshtml
@using WebsiteCongChung.Models
@model TaiSanViewModel
@{
    using (Html.BeginForm("InPhieuYeuCau", "HopDong"))
    {

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-2 pull-right">
                        <a class="btn btn-default btn-group-justified" onclick="KiemTraTS()">Kiểm tra tài sản</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label">Số Sổ</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>

                    <label class="col-md-2 control-label">Số Vào Sổ</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label">Nhà Số</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>

                    <label class="col-md-2 control-label">Đường</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label">Phường</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>

                    <label class="col-md-2 control-label">Quận/Huyện</label>
                    <div class="col-md-4">
                        @Html.TextBoxFor(m => m.TenTaiSan, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TenTaiSan, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    }
}